project:
  type: website
  output-dir: docs

website:
  title: "ryleesheils"
  navbar:
    collapse: false
    left:
      - href: index.qmd
        text: Landing
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: free.qmd
        text: Free-for-all

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true