project:
  type: website
  output-dir: docs

website:
  title: "Rylee Sheils"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: free.qmd
        text: Interests
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual